//! TypeScript emitter.
//!
//! Output is intentionally simple: one `export const <name> = { ... } as const`
//! per scale. Keys are quoted only when they don't form a valid JS identifier
//! (e.g. `'2xl'`). Values are always single-quoted strings — VE accepts CSS
//! values as strings everywhere.

use crate::{Pair, Spec};
use std::fmt::Write;

#[must_use]
pub fn typescript(spec: &Spec) -> String {
	let mut out = String::with_capacity(4096);

	writeln!(out, "// AUTO-GENERATED by `tokens-gen` — DO NOT EDIT.").unwrap();
	writeln!(out, "// Source: tokens-gen/src/lib.rs · regenerate with `bun run codegen`.").unwrap();
	writeln!(out, "// biome-ignore-all lint/style/useNamingConvention: keys mirror Rust scale names.").unwrap();
	writeln!(out).unwrap();

	emit(&mut out, "breakpoints", &spec.breakpoints);
	emit(&mut out, "space", &spec.space);
	emit(&mut out, "fontSize", &spec.font_size);
	emit(&mut out, "fontWeight", &spec.font_weight);
	emit(&mut out, "lineHeight", &spec.line_height);
	emit(&mut out, "letterSpacing", &spec.letter_spacing);
	emit(&mut out, "radius", &spec.radius);
	emit(&mut out, "shadow", &spec.shadow);
	emit(&mut out, "duration", &spec.duration);
	emit(&mut out, "easing", &spec.easing);
	emit(&mut out, "measure", &spec.measure);
	emit(&mut out, "fluid", &spec.fluid);
	emit(&mut out, "columns", &spec.columns);
	emit(&mut out, "zIndex", &spec.z_index);

	emit_helper_types(&mut out);

	out
}

fn emit(out: &mut String, name: &str, pairs: &[Pair]) {
	writeln!(out, "export const {name} = {{").unwrap();
	for (key, value) in pairs {
		let k = format_key(key);
		writeln!(out, "\t{k}: '{value}',").unwrap();
	}
	writeln!(out, "}} as const;").unwrap();
	writeln!(out).unwrap();
}

fn emit_helper_types(out: &mut String) {
	let scales = [
		"breakpoints",
		"space",
		"fontSize",
		"fontWeight",
		"lineHeight",
		"letterSpacing",
		"radius",
		"shadow",
		"duration",
		"easing",
		"measure",
		"fluid",
		"columns",
		"zIndex",
	];

	writeln!(out, "// Per-scale key unions (for type-safe lookups).").unwrap();
	for name in scales {
		let pascal = pascal_case(name);
		writeln!(out, "export type {pascal}Key = keyof typeof {name};").unwrap();
	}
}

fn format_key(key: &str) -> String {
	if is_valid_ident(key) {
		key.to_string()
	} else {
		format!("'{key}'")
	}
}

fn is_valid_ident(s: &str) -> bool {
	let mut chars = s.chars();
	match chars.next() {
		Some(c) if c.is_ascii_alphabetic() || c == '_' || c == '$' => {}
		_ => return false,
	}
	chars.all(|c| c.is_ascii_alphanumeric() || c == '_' || c == '$')
}

fn pascal_case(s: &str) -> String {
	let mut out = String::with_capacity(s.len());
	let mut upper = true;
	for c in s.chars() {
		if c == '_' || c == '-' {
			upper = true;
			continue;
		}
		if upper {
			out.extend(c.to_uppercase());
			upper = false;
		} else {
			out.push(c);
		}
	}
	out
}

#[cfg(test)]
mod tests {
	use super::*;

	#[test]
	fn identifier_keys_unquoted() {
		assert_eq!(format_key("xs"), "xs");
		assert_eq!(format_key("base"), "base");
	}

	#[test]
	fn non_identifier_keys_quoted() {
		assert_eq!(format_key("2xl"), "'2xl'");
		assert_eq!(format_key("3xs"), "'3xs'");
	}

	#[test]
	fn pascal_case_works() {
		assert_eq!(pascal_case("fontSize"), "FontSize");
		assert_eq!(pascal_case("breakpoints"), "Breakpoints");
		assert_eq!(pascal_case("font_weight"), "FontWeight");
	}
}
